# src/core/ports/base_repository.py
from typing import Protocol, List, Optional, TypeVar, Generic

T = TypeVar('T')


class BaseRepository(Protocol, Generic[T]):
    def get_all(self) -> List[T]: ...
    def get_by_id(self, id: int) -> Optional[T]: ...
    def create(self, **kwargs) -> T: ...
    def update(self, id: int, **kwargs) -> T: ...
    def delete(self, id: int) -> None: ...
