# src/core/ports/column_repository.py
from typing import Protocol, List, Any, Optional
from ..domain.entities import Column as ColEntity


class ColumnRepository(Protocol):
    def get_by_id(self, column_id: int) -> Optional[ColEntity]: ...
    def list_by_taskboard(self, taskboard_id: int) -> List[ColEntity]: ...
    def create(self, taskboard_id: int, title: str, position: Any) -> ColEntity: ...
    def update(self, column_id: int, **kwargs) -> ColEntity: ...
    def delete(self, column_id: int) -> None: ...
