# src/core/ports/project_member_repository.py
from typing import Protocol, List, Optional
from core.domain.entities import ProjectMember as PM
from core.domain.value_objects.permission_key import PermissionKey


class ProjectMemberRepository(Protocol):
    def get_by_id(self, member_id: int) -> Optional[PM]: ...
    def list_by_project(self, project_id: int) -> List[PM]: ...
    def list_by_user(self, user_id: int) -> List[PM]: ...
    def create(self, user_id: int, project_id: int,
               initial_permissions: List[PermissionKey]) -> PM: ...

    def update(self, member_id: int, **kwargs) -> PM: ...
    def delete(self, member_id: int) -> None: ...

    def set_permissions(self, member_id: int,
                        permissions: List[PermissionKey]) -> None: ...
