# src/core/ports/user_repository.py
'''
'''
from typing import Protocol, Optional
from adapters.outbound.persistence.models.user import User as UserModel


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[UserModel]: ...
    def get_by_username(self, username: str) -> Optional[UserModel]: ...
    def create(self, username: str, email: str, password_hash: str) -> UserModel: ...
    def block(self, user_id: int) -> None: ...
